added a dependency

diff --git a/manifest b/manifest
--- a/manifest
+++ b/manifest
@@ -197,7 +197,7 @@ __services () {
 # composer global
 __composer() {
   type compsoser &>/dev/null
-  [[ $? -ne 0 ]] && printf "I require  but it's not installed. Aborting."; exit 1;
+  [[ $? -ne 0 ]] && printf "I require %s but it's not installed. Aborting." "${FUNCNAME[0]#__}"; exit 1;
   if [[ -z "${COMPOSER_HOME}" ]];then
     COMPOSER_HOME="${HOME}/composer.json"
   fi
@@ -504,6 +504,12 @@ else
 	               ;;
     esac
   done
+  #
+  #########
+  # LOAD DEPENDENCIES
+  ########
+  source ./deps/progress-bar.sh
+  #
   #
   #
   for tryFunction in "${@}"
