rough inclusion of pip very rough

diff --git a/manifest b/manifest
--- a/manifest
+++ b/manifest
@@ -255,6 +255,15 @@ EOM
   notify "${FUNCNAME[0]} is complete."
 }
 #
+__pip() {
+  type pip &>/dev/null  || { echo >&2 "I require pip, but it's not installed. Aborting."; exit 1; }
+  notify "Generating ${FUNCNAME[0]#__} manifest..."
+  pip list --format=columns > "${_BASE}pip.txt"
+  notify "done."
+
+}
+
+
 # # manifest of all installed macports ports
 __port() {
   if [[ $1 == 'help' ]]; then
