working on listing of installed and not installed

diff --git a/manifest b/manifest
--- a/manifest
+++ b/manifest
@@ -200,7 +200,7 @@ __services () {
 # composer global
 __composer() {
   type compsoser &>/dev/null
-  [[ $? -ne 0 ]] && printf "I require GEM but it's not installed. Aborting."; exit 1;
+  [[ $? -ne 0 ]] && printf "I require  but it's not installed. Aborting."; exit 1;
   if [[ -z "${COMPOSER_HOME}" ]];then
     COMPOSER_HOME="${HOME}/composer.json"
   fi
@@ -454,8 +454,18 @@ else
       f)  #set option "f"
 	shift $((OPTIND-1))
 	if [[ -z "${1}" ]]; then
-	  compgen -A function | grep '__' | sed 's/__//g'
-
+	  arr=(`compgen -A function | grep '__' | sed 's/__//g'`)
+    printf '%-14s status\n' "bin"
+    printf '%.0s-' {1..30}; echo
+    for tttt in "${arr[@]}"
+    do
+      type -p "${tttt}" &>/dev/null
+      if [[ $? == 0 ]]; then
+        printf '%-14s found\n' "${tttt}"
+      else
+        printf '%-14s not found\n' "${tttt}"
+      fi
+    done
 	else
 	  if ( compgen -A function "__${1}"); then
 	    eval "__${1}" 'help'
@@ -466,35 +476,35 @@ else
 	exit 0
 	;;
       i) #--init
-	echo "Initialize configuration file?" >/dev/tty
-	exit 0
-	;;
-      n) # use osx notifications
-	shift $((OPTIND-1))
-	break
-	;;
-      q) # set 'q'
-	__manifest &> /dev/null &
-	exit 0
-	;;
-      t) # set 't'
-	shift $((OPTIND-1))
-	sytem=1
-	__manifest
-	;;
-      v) #set option "v"
-	printf 'v0.8.9 β\n' >/dev/tty
-	exit 0
-	;;
-      h)  #show help
-	func_menu_help
-	exit 0
-	;;
-      \?) #unrecognized option - show help
-	printf 'Unknown option.\n'
-	printf 'Use -h for helpful info.\n'
-	exit 2
-	;;
+	      echo "Initialize configuration file?" >/dev/tty
+	      exit 0
+	               ;;
+               n) # use osx notifications
+	               shift $((OPTIND-1))
+	               break
+	               ;;
+               q) # set 'q'
+	               __manifest &> /dev/null &
+	               exit 0
+	               ;;
+               t) # set 't'
+	               shift $((OPTIND-1))
+	               sytem=1
+	               __manifest
+	               ;;
+               v) #set option "v"
+	               printf 'v0.8.9 β\n' >/dev/tty
+	               exit 0
+	               ;;
+               h)  #show help
+	               func_menu_help
+	               exit 0
+	               ;;
+               \?) #unrecognized option - show help
+	               printf 'Unknown option.\n'
+	               printf 'Use -h for helpful info.\n'
+	               exit 2
+	               ;;
     esac
   done
   #
